import vehiculos_clases as vc

my_vehicleNATO_SPAAG = vc.Vehiculo("IFV-6a 'Cheetah'", "OTAN", "Antiaéreo")
my_vehicleNATO_SPG = vc.Vehiculo("M4 'Scorcher'", "OTAN", "Artillería")
my_vehicleNATO_SPGR = vc.Vehiculo("M5 'Sandstorm'", "OTAN", "Artillería de cohetes")
my_vehicleNATO_FighterAT = vc.Vehiculo("A-164 'Wipeout'", "OTAN", "Ataque")
my_vehicleNATO_Fighter = vc.Vehiculo("F/A-181 'Black Wasp II'", "OTAN", "Polivalente")
my_vehicleNATO_CarTR = vc.Vehiculo("HEMTT", "OTAN", "Camion")
my_vehicleNATO_CarMR = vc.Vehiculo("Hunter", "OTAN", "MRAP")
my_vehicleNATO_CarLSV = vc.Vehiculo("Prowler", "OTAN", "MRAP")
my_vehicleNATO_ATV = vc.Vehiculo("Moto de cuatro ruedas", "OTAN/CSAT/AAF", "Moto")
my_vehicleNATO_DronesQ = vc.Vehiculo("AR-2 'Darter'", "OTAN/AAF", "Dron")
my_vehicleNATO_DronesR = vc.Vehiculo("MQ-4A 'Greyhawk'", "OTAN/AAF", "Dron de ataque")
my_vehicleNATO_DronesRC = vc.Vehiculo("UCAV Sentinel", "OTAN", "Dron de ataque embarcado")
my_vehicleNATO_HeloATL = vc.Vehiculo("AH-9 'Pawnee'", "OTAN", "Helicóptero de ataque ligero")
my_vehicleNATO_HeloAT = vc.Vehiculo("AH-99 'Blackfoot'", "OTAN", "Helicóptero de ataque")
my_vehicleNATO_HeloTH = vc.Vehiculo("CH-67 'Huron'", "OTAN", "Helicóptero de transporte pesado")
my_vehicleNATO_HeloL = vc.Vehiculo("MH-9 'Hummingbird'", "OTAN", "Helicóptero ligero")
my_vehicleNATO_HeloT = vc.Vehiculo("UH-80 'Ghosthawk'", "OTAN", "Helicóptero de transporte")
my_vehicleNATO_MBT = vc.Vehiculo("M2A1 'Slammer'", "OTAN", "Carro de combate principal")
my_vehicleNATO_MBTUP = vc.Vehiculo("M2A4 'Slammer UP'", "OTAN", "Carro de combate principal de combate urbano")
my_vehicleNATO_SUB = vc.Vehiculo("SDV", "OTAN/CSAT/AAF", "Submarino")
my_vehicleNATO_APC = vc.Vehiculo("AMV-7 'Marshall'", "OTAN", "Vehículo de Transporte de Personal")
my_vehicleNATO_IFV = vc.Vehiculo("IFV-6c 'Panther'", "OTAN", "Vehículo de Combate de Infantería")

print(my_vehicleNATO_SPAAG)
print(my_vehicleNATO_SPG)
print(my_vehicleNATO_SPGR)
print(my_vehicleNATO_FighterAT)
print(my_vehicleNATO_Fighter)
print(my_vehicleNATO_CarTr)
print(my_vehicleNATO_CarMR)
print(my_vehicleNATO_DronesQ)
print(my_vehicleNATO_DronesR)
print(my_vehicleNATO_DronesRC)
print(my_vehicleNATO_HeloATL)
print(my_vehicleNATO_HeloAT)
print(my_vehicleNATO_HeloTH)
print(my_vehicleNATO_HeloL)
print(my_vehicleNATO_HeloT)
print(my_vehicleNATO_MBT)
print(my_vehicleNATO_MBTUP)
print(my_vehicleNATO_SUB)
print(my_vehicleNATO_APC)
print(my_vehicleNATO_VCI)

